# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!

target 'ProjectArmadillo iOS' do
	pod 'Mixpanel'
end

target 'ProjectArmadillo Android' do

end

target 'ProjectArmadillo Mac' do

end
